/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SeRouteImport } from './routes/se'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppBeboereRouteImport } from './routes/_app.beboere'
import { Route as AppByttRouteImport } from './routes/_app.bytt'
import { Route as AppKalenderRouteImport } from './routes/_app.kalender'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SeRoute = SeRouteImport.update({
  id: '/se',
  path: '/se',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBeboereRoute = AppBeboereRouteImport.update({
  id: '/beboere',
  path: '/beboere',
  getParentRoute: () => AppRoute,
} as any)
const AppByttRoute = AppByttRouteImport.update({
  id: '/bytt',
  path: '/bytt',
  getParentRoute: () => AppRoute,
} as any)
const AppKalenderRoute = AppKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/se': typeof SeRoute
  '/beboere': typeof AppBeboereRoute
  '/bytt': typeof AppByttRoute
  '/kalender': typeof AppKalenderRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/se': typeof SeRoute
  '/beboere': typeof AppBeboereRoute
  '/bytt': typeof AppByttRoute
  '/kalender': typeof AppKalenderRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/se': typeof SeRoute
  '/_app/beboere': typeof AppBeboereRoute
  '/_app/bytt': typeof AppByttRoute
  '/_app/kalender': typeof AppKalenderRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/se' | '/beboere' | '/bytt' | '/kalender'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/se' | '/beboere' | '/bytt' | '/kalender' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/se'
    | '/_app/beboere'
    | '/_app/bytt'
    | '/_app/kalender'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SeRoute: typeof SeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/se': {
      id: '/se'
      path: '/se'
      fullPath: '/se'
      preLoaderRoute: typeof SeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beboere': {
      id: '/_app/beboere'
      path: '/beboere'
      fullPath: '/beboere'
      preLoaderRoute: typeof AppBeboereRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bytt': {
      id: '/_app/bytt'
      path: '/bytt'
      fullPath: '/bytt'
      preLoaderRoute: typeof AppByttRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kalender': {
      id: '/_app/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AppKalenderRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBeboereRoute: typeof AppBeboereRoute
  AppByttRoute: typeof AppByttRoute
  AppKalenderRoute: typeof AppKalenderRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBeboereRoute: AppBeboereRoute,
  AppByttRoute: AppByttRoute,
  AppKalenderRoute: AppKalenderRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SeRoute: SeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
